log_level: "none" # Notice: for client use, please set log_level to "error"

# Control System Layer --------------------------------------------------------
device_connected: true

hardware_type: "X64"
hardware_layer: "fourier-core"

resource:
  path: "~/fourier-grx/resource/n1"

zenoh:
  path: "~/fourier-grx/resource/zenoh"

# Robot Layer -----------------------------------------------------------------
robot:
  name: "N1"
  mechanism: ""
  control_period: 0.0025

# Component Layer -------------------------------------------------------------
sensor_usb_imu:
  comm_enable: [
    true
  ]

actuator:
  comm_enable: [
    # left leg
    true, true, true, true, true, true,
    # right leg
    true, true, true, true, true, true,
    # waist
    true,
    # left arm
    true, true, true, true, true,
    # right arm
    true, true, true, true, true,
  ]

# Hardware Layer ---------------------------------------------------------------
fi_fsa:
  version: "v2_async"
